### ISSUE TITLE
Game hangt in Horsey cinematic vast bij verslaan van Horsey en tegelijkertijd game over gaan

### ISSUE THREAD

**Issue by jjmhalew** [Sheepolution/lekker-spelen-origins#1]
De camera is ingezoomd zoals bij de cinematic en besturen is nog mogelijk. Horsey lijkt gespawned maar doet niets.

![IMG-20240629-WA0000.jpg](https://github.com/Sheepolution/lekker-spelen-origins/assets/38460550/4ae388a5-8159-4b89-8657-e7c3b7840c1f)

**Comment by Sheepolution** [comment]
Wat als je de game opnieuw opstart?

**Comment by jjmhalew** [comment]
Wanneer een vriend en ik de game opnieuw opstarten blijven we nog steeds op bovenstaand scherm uitkomen.
De save lijkt iets te bevatten van de boss fight door ons 'gelijkspel' gok ik.

Overigens super vette game! Echt tof gemaakt qua art, muziek, gameplay, story, level design, referenties en humor :) Hier kan ik nou echt van genieten!

**Comment by Sheepolution** [comment]
En je kan ook niet links of rechts de deur uitlopen? Ik kan me wel iets voorstellen dat iets fout zou gaan bij het tegelijkertijd doodgaan met Horsey, maar deze specifieke situatie vind ik dan wel vreemd. Het lijkt erop dat de intro cutscene geïnitialiseerd wordt, maar vervolgens niet uitgevoerd, en ik zou niet weten waarom niet.

**Comment by jjmhalew** [comment]
De deur links of rechts uitlopen hebben we geprobeerd, maar lukt helaas ook niet. Het lijkt er inderdaad op dat de cutscene geïnitialiseerd wordt, maar niet uitgevoerd wordt. En desnoods starten we een new game; ik kan me voorstellen dat dit een lange debug sessie kan opleveren voor een edge case die niet vaak voorkomt

**Comment by Sheepolution** [comment]
Ik heb de bug (waarschijnlijk) opgelost, maar het is inderdaad vervelend om jouw situatie nu op te lossen zonder heel het spel te breken. Als je me een bericht stuurt op Discord kan ik je wel een custom build sturen zodat je uit deze situatie kan.

**Comment by jjmhalew** [comment]
Nice! Als het niet teveel moeite kost om een nieuwe custom build te maken en op te sturen, dan zou dat geweldig zijn! Ik neem aan dat je op Discord ook Sheepolution heet; ik heb een verzoek gestuurd onder de naam Pipo / jjmhalew
